version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
      - /code/venv
    ports:
      - 8080:8080
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    stdin_open: true
    tty: true